### ISSUE TITLE
Feature: Tidy 5e Sheets Compatibility

### ISSUE THREAD

**Issue by kgar** [mysurvive/so-inspired#1]
Hello, I am the author of the new [Tidy 5e Sheets rewrite](<https://github.com/kgar/foundry-vtt-tidy-5e-sheets/>). The new sheets are using svelte and have their own rendering rules and HTML structure, so they do not integrate automatically the way default and default-like sheets do.

As a result, I have been going from module to module to request the opportunity to establish intentional compatibility with my sheets. I have an [API](https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html) for injecting content, and I will gladly volunteer a pull request and/or sample code for integrating.

Wherever possible, I try to make integration out-of-the-way and minimal, and my integration API / offerings are under active development and evolving based on module author needs.

I hope to work together. Let me know your thoughts.

**Comment by mysurvive** [comment]
Happy to fix compatibility! As you can see from the code, it's just really simply injecting some HTML into the character sheet using jquery. If you have a quick fix, I have no problem accepting a PR, or if you want to point me to the right parts of the API, that would work as well.

**Comment by kgar** [comment]
Awesome! You'll be making a mutual user of ours very happy. They wanted exactly what your module offers in new Tidy.
I've been playing some SWADE recently, and multiple benny-like inspo's is pretty nice.
I submitted a PR linked to this issue. Feel free to make any changes you see fit. I put some comments and notes in the PR just to explain some stuff I did.
