### ISSUE TITLE
Feature Request: Way to shut off errors.

### ISSUE THREAD

**Issue by MythicalRollers** [mysurvive/so-inspired#12]
I wonder if it would be possible to have error reporting off, unless debug is enabled in the configuration.  Reason being, some of my PC's have become NPC's and as such do not have players assigned.  But every time I open the character sheet, the error is noted in the console.  This is just extra noise when trying to figure out other module issues.
I really like this module otherwise, thank you for your work on it.
If it matters:
Foundry: 11.315
D&D: 3.2.1
So Inspired!: 0.4.0
![image](https://github.com/user-attachments/assets/5cb8db08-1443-4568-95ce-1f945fffedc9)

**Comment by mysurvive** [comment]
I'm having trouble reproducing this. When there isn't a user assigned to a character, it doesn't continue for me. Did you go into the user configuration and unassign the character from the user, or did you  unassign a user some other way?

**Comment by MythicalRollers** [comment]
All modules off except for SI.
![image](https://github.com/user-attachments/assets/a1a240b2-c223-4f4a-aa99-9ca7f07f2dd7)
Create new Actor as a "player character" do not assign a player to it, error in console.  I will now update the module to see if there are any changes with the new version.
*Update* Never mind I cannot update the module beyond 4.0 as I am on V11.

**Comment by mysurvive** [comment]
I can't replicate on v12 and I'm not making any more v11 releases. You might be able to change line 378 from `if (user?.character.sheet.rendered) ` to `if (user?.character.sheet?.rendered) `
