### ISSUE TITLE
Not working - Never mind :)

### ISSUE THREAD

**Issue by arcanjl** [mysurvive/so-inspired#18]
Is it because I updated to 5e 3.3? 
It is now completely missing from the character sheet, and the original insp is back up at the top.
![image](https://github.com/user-attachments/assets/d8450f8c-d384-44d1-80c2-e47a6d1d5bd3)

**Comment by arcanjl** [comment]
They had to own it :(

**Comment by mysurvive** [comment]
Yep! Gotta own the character :D
