### ISSUE TITLE
[Feature Request] Enable GM to set inspiration bar color for all users

### ISSUE THREAD

**Issue by nschoenwald** [mysurvive/so-inspired#19]
Currently, the inspiration bar color is a client side setting that is behind a pop-up that does not work with the module Force Client Settings. So I can't set the color of the bar for my players. It would be great if this could be added as an option.

**Comment by mysurvive** [comment]
It's working fine for me? I just tested a color change like 3x in a row and it changed on a non-gm user each time.

**Comment by mysurvive** [comment]
![image](https://github.com/user-attachments/assets/67d59b12-a1ff-4b6c-87ec-8780e22a117a)
1st color
![image](https://github.com/user-attachments/assets/9a0a0637-50ae-497e-aa4d-a07d7d045a75)
![image](https://github.com/user-attachments/assets/c95cd0cd-a38c-4d61-8916-dd82cc0f6d62)

2nd color
![image](https://github.com/user-attachments/assets/e7245625-1087-40bc-aca6-5c6a86aafe73)
![image](https://github.com/user-attachments/assets/fb420791-6a05-49af-9ef9-0b88b69e3c2f)

3rd color
![image](https://github.com/user-attachments/assets/f735a232-0b2d-4598-9af1-e09b47ab5cd9)
![image](https://github.com/user-attachments/assets/cac0ff22-963f-4232-838e-7f1939755b05)


I didn't change anything on a connected client's settings any of the times, only on the GM's settings.

**Comment by nschoenwald** [comment]
Are you testing in the same client? Because the setting is saved in the client, so won't be applied to connecting players in a real world scenario. That's my problem.

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/61116c4d-2ed8-4d05-98cf-65ba86843946">
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/3c299d0b-121d-4795-b4ca-1a3bc6f7a8ba">

**Comment by mysurvive** [comment]
Did you refresh the page? It's working fine for me. Even opened another computer and connected and experienced it working still.
You can test by running `game.settings.get("so-inspired","inspirationBackgroundColor")` in the console. The results of that setting are what Force Client Settings forces on connected clients. The setting being set by a menu doesn't change how that works.
![soinspired](https://github.com/user-attachments/assets/0887b9d3-0584-4ecd-a9d6-7431605dd424)
Sorry for the small gif. Github has a tiny limit that kind of restricts the size/quality of a gif I can put in here.

**Comment by nschoenwald** [comment]
Huh. Not sure what I'm doing wrong. Maybe you can spot something in this screen recording?

https://youtu.be/hWpxadsYV90

**Comment by nschoenwald** [comment]
Ah, I figured it out! I had to go into the Force Client Settings menu and set the setting to force there. Now it works. Thank you for your time!
