### ISSUE TITLE
[Feature Request]  Add inspiration on d20 checks that are 1s

### ISSUE THREAD

**Issue by thepting** [mysurvive/so-inspired#20]
Hey, was wondering if you could consider adding a feature request for one of the UA rules my table really liked:

When a player rolls a 1 on a D20 check, they get an inspiration point.

It kinda takes the edge off of the fail/fumble, and (more importantly for me) injects some automated inspiration in the game because I'm pretty bad at remembering to grant it in-the-moment.

Love the module, as do my players.  Cheers!

**Comment by mysurvive** [comment]
This is a very niche rule that isn't really in scope for the module, sorry. I'm really glad you like the module though!
