### ISSUE TITLE
[Bug] Not compatible with DnD5e 3.1.2

### ISSUE THREAD

**Issue by marcstraube** [mysurvive/so-inspired#6]
I run FoundryVTT 11.315 and DnD5e 3.1.2 and So Inspired is the only active module. It seems that it does not work with the current DnD system. At least I can not find an input field or similar for entering the amount of inspiration points.

It would also be a nice to show a screenshot of the changes this module makes from the standard Actor form.

**Comment by mysurvive** [comment]
I realize I'm very late seeing this, but can you let me know what sheet you're having issues with? 
![image](https://github.com/mysurvive/so-inspired/assets/16602055/49f04f18-d44b-4c07-aed3-be3ec78be1a4)
![image](https://github.com/mysurvive/so-inspired/assets/16602055/2b2e6b8b-281c-47ab-a9da-323c7cc81014)
![image](https://github.com/mysurvive/so-inspired/assets/16602055/dab4acba-a61d-4f04-aa97-0a2a93a4fe61)

**Comment by Geiun** [comment]
I might be running into the same issue. Otherwise, there's some step during setup I need to do that I can't find instructed anywhere. I have tried this with legacy, tidy, and the default. None of them work. The default and legacy still show a checkbox for a single value no matter what cap I define. Tidy doesn't show anything at all unless I disable this module.

**Comment by mysurvive** [comment]
Are there any errors in console? I play in a 5e game on Thursdays and those screenshots are from that session so I'm curious. There shouldn't be any setup, just turn the module on and go.

**Comment by mysurvive** [comment]
I made a fresh world, and it is still working. Have either of you/your players claimed their character?

![image](https://github.com/mysurvive/so-inspired/assets/16602055/0f9c71c2-15e2-40c8-881f-2c4e136d0242)
![image](https://github.com/mysurvive/so-inspired/assets/16602055/0544fb31-18f4-42ed-99b8-e304bb80f392)

**Comment by Geiun** [comment]
Mine is a fresh world as well. Players hadn't claimed anything. I just created a player and assigned the sheet to them, then I saw this in the console:

![image](https://github.com/mysurvive/so-inspired/assets/7614958/4667e3a5-0565-4fe2-ac7d-b89aa7c8150a)

**Comment by Geiun** [comment]
Ah, wait. Interesting... I get an inspiration counter but only after a user "selects" a character. Ownership isn't enough. And if they change character it gets removed from one sheet and shows up on the other. Is there a reason why inspiration behaves this way? Without So Inspired inspiration exists on the character sheet regardless of all this.

**Comment by mysurvive** [comment]
The module hides the default inspiration area on the sheet.

A player needs to claim a character for the inspiration counter to work. You're right, ownership is not enough.

**Comment by mysurvive** [comment]
I think we've gotten to the root of the issue, and I put some information on the README, so I'm going to close this issue.
